version: '3.9'

x-depends_on:
  &depends_on
  kong-database:
    condition: service_healthy

x-kong_environment:
  &kong_environment
  environment:
    - KONG_DATABASE=postgres
    - KONG_PG_HOST=kong-database
    - KONG_PG_DATABASE=kong
    - KONG_ADMIN_LISTEN=0.0.0.0:8001

services:
  kong-database:
    image: postgres
    container_name: kong-postgres
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  kong-migration:
    image: kong
    container_name: kong-migration
    command: kong migrations bootstrap
    depends_on:
      <<: *depends_on
    <<: *kong_environment

  kong:
    image: kong
    container_name: kong
    restart: always
    depends_on:
      <<: *depends_on
      kong-migration:
        condition: service_started
    links:
      - kong-database:kong-database
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444
    <<: *kong_environment
